### ISSUE TITLE
Invalid Query: column is of type date but expression is of type text

### ISSUE THREAD

**Issue by rhenriquez28** [ts-safeql/safeql#159]
**Describe the bug**
If I have a column of type DATE and I'm doing an INSERT statement with a string value of format "YYYY-MM-DD" I get the error: `Invalid Query: column "<column-name>" is of type date but expression is of type text`.

I don't have any INSERT statements with a TIMESTAMP column but it's worth checking if the same behavior doesn't happen in that case as well

**To Reproduce**
1. Have a table with a column of type DATE
2. Write an INSERT or UPDATE statement for it
3. See the error

**Expected behavior**
I should be able to insert the value since the string is an actual date

**Screenshots**
<img width="686" alt="Screenshot 2023-05-11 at 8 36 46 PM" src="https://github.com/ts-safeql/safeql/assets/22778956/e0bb7280-ba3a-4d1f-9609-12a4eba9360f">

**Desktop (please complete the following information):**
 - OS: macOS 13.3.1 
 - PostgreSQL version 14.1
 - Version 1.1.3

**Comment by Newbie012** [comment]
Hi @rhenriquez28 

Since SafeQL doesn't run in your runtime, it doesn't have access to your string to verify whether it's an actual date string. For type safety, I took the strict approach and disallowed comparing date to string. To tackle this, there are a few options you can do:

### Cast your string with the `::notation`

```
function run() {
  const date = moment().format('YYYY-MM-DD');
  return sql`INSERT INTO tbl (dtsigned) VALUES (${date}::date)`;
}
```

### Wrap your date with a type and use the [`overrides.types`](https://safeql.dev/api/#connections-overrides-types-optional) option

Since SafeQL doesn't know the actual value, it relies on TypeScript types. This means we can tell SafeQL what is a date and what's not:

```ts
type LocalDate = string & { __type: "LocalDate" }

function run() {
  const date = moment().format('YYYY-MM-DD') as LocalDate
  return sql`INSERT INTO tbl (dtsigned) VALUES (${date})`; // no need to ::cast.
}
```

```json
{
  "connections": {
    // ...connection props
    "overrides": {
      "types": {
        "date": "LocalDate",
      }
    }
  }
}
```

Personally, I'm a fan of [js-joda](https://js-joda.github.io/js-joda/) which would probably be superseded by the new Temporal API.
It has built-in types (such as LocalDate, LocalDateTime, Instant (UTC), etc.) which work seamlessly without the need to format the types manually.

**Comment by rhenriquez28** [comment]
Very thoughtful. Thank you very much for the reply and the alternatives you provided 😁
