### ISSUE TITLE
Aggregation on nullable fields lead to a wrong type error

### ISSUE THREAD

**Issue by MatanOligo** [ts-safeql/safeql#167]
**Describe the bug**
Type suggestion is wrong, we get a lint error which we shouldn't.

**To Reproduce**
I guess it happens when we use `max(X)` as aggregate, on a nullable field.

**Expected behavior**
`lastExecutedAt` is a nullable field, so `max(lastExecutedAt)` may be null as well, but safeql forces me to declare this field as `Date`, while I would expect it to be `Date | null`.

**Screenshots**
<img width="956" alt="Screenshot 2023-07-03 at 12 18 37" src="https://github.com/ts-safeql/safeql/assets/132813026/5f187f05-4dcf-4411-b1b1-b25a9a04cee0">

<img width="1040" alt="Screenshot 2023-07-05 at 13 08 57" src="https://github.com/ts-safeql/safeql/assets/132813026/defbc839-554e-4f41-913b-dc3dae70d7d2">

<img width="701" alt="Screenshot 2023-07-05 at 13 09 52" src="https://github.com/ts-safeql/safeql/assets/132813026/b2686d87-4274-491c-9a41-2902b1d2a4cb">

**Desktop (please complete the following information):**
 - OS: `macOS`
 - PostgreSQL version: `irrelevant`
 - Version: `eslint-plugin 1.1.4`

**Comment by Newbie012** [comment]
That's interesting.
Currently, the plugin assumes each row is non-nullable until proven otherwise (either by looking at the table column definition or by a join type if exists).

Assuming the opposite (nullable until proven otherwise) will solve that problem, but will introduce odd cases

```ts
// ex1 - we know for a fact that num is non-nullable here
sql<{ num: number | null }>`select 1 as num`

// ex2 - we know for a fact that count never returns null.
sql<{ num: number | null }>`select count(1)`
```

The only solution I could do is to assume the opposite (nullable until proven otherwise) and then add another layer of checks to determine whether a column is non-nullable based on the parsed query.

Since it'll take time to implement, in the meanwhile, I can add a flag called `expirmentalStrictNull` which assumes every column is nullable until proven otherwise. The only false-negative cases will be the examples I've written above. Will it temporarily solve your issue?
