### ISSUE TITLE
Use `bigint` type for Postgres `BIGINT`

### ISSUE THREAD

**Issue by galah92** [ts-safeql/safeql#184]
Looks like Postgres `BIGINT` is being parsed as `string`. I think it should be parsed as `bigint` for a NodeJS version that supports it.

**Describe alternatives you've considered**

I currently override it with the following configuration:
```json
"overrides": {
  "types": {
    "bigint": "bigint"
  }
```

Thank you.

P.S: amazing library, one I wish I would've written myself 👍

**Comment by Newbie012** [comment]
It really depends on the library that you're using. From what I tested, [`postgres`](https://github.com/porsager/postgres#numbers-bigint-numeric) and [`pg`](https://github.com/brianc/node-pg-types/issues/78#issuecomment-540132433) return it as a string.

Until these two packages won't switch (due to their legitimate reasons) to BigInt, I prefer keeping `string` as the default
