### ISSUE TITLE
The package not install on Node 18.18.0 and 20.12.0 (LTS)

### ISSUE THREAD

**Issue by PedroGuilhermeFariaDuarte** [ts-safeql/safeql#215]
**Describe the bug**

The command 
```
 npm i @ts-safeql/eslint-plugin
```
do not work because always get a erro with **node-pre-gyp** package

With others packages always install with success

**To Reproduce**
Just exec the command  **npm i @ts-safeql/eslint-plugin** with Node on 18 or 20 version

**Screenshots**
![image](https://github.com/ts-safeql/safeql/assets/16112395/23f0ea27-016d-4555-8809-0c60f55a373e)

System Linux 5.15.146.1-microsoft-standard-WSL2

**Comment by karlhorky** [comment]
Can you show the complete logs of the installation? (not as a screenshot, because that is not searchable / copyable)

`node-pre-gyp` sounds unrelated to SafeQL. `node-gyp` (without the `pre`) errors would be a problem potentially related to a native dependency called [`libpg-query`](https://www.npmjs.com/package/libpg-query), but the screenshot in your issue above is not helpful - it doesn't show the actual error message.

**Comment by Newbie012** [comment]
closing due to no response from the OP
