### ISSUE TITLE
[feature request] Allow to cast a database type to something else

### ISSUE THREAD

**Issue by gajus** [ts-safeql/safeql#290]
Started as a discussion topic:

### Discussed in https://github.com/ts-safeql/safeql/discussions/289

<div type='discussions-op-text'>

<sup>Originally posted by **gajus** December  2, 2024</sup>
I am getting a lot of error like:

> Invalid Query: column "category" is of type notification_category but expression is of type text
> Invalid Query: column "due_at" is of type date but expression is of type text

I know I can fix it like,

```ts
${'OTHER'}::notification_category,
${dayjs().add(1, 'day').format('YYYY-MM-DD')}::date,
```

but there are thousands of these, and really not much value in adding this code.

Is there a way to configure that `notification_category` should be treated as text?

I think what I am asking is the inverse of https://safeql.dev/api/#connections-overrides-types-optional, and it appears to be not supported.</div>

---

But yeah, for types like `uuid`, I would just want them to be `text`, as opposed to some esoteric type.

```ts
${foreignCrunchbaseUuid}::uuid
```

Casting here does not add any value that I can think of.

**Comment by gajus** [comment]
Ended up just adding `::uuid` / `::date` everywhere. No big deal.

**Comment by naftis** [comment]
I'm facing this as well. Is casting the recommended way, if so, could it be added to the docs?

**Comment by Newbie012** [comment]
I wouldn't say it's the "recommended", but it's just one way doing it. The "constraint" behind this issue is that whenever the rule encounters the following code:

```ts
function run(value: string) {
  return sql`select * from tbl where id_as_uuid = ${value}`
}
```

it has to has to transpile it to a valid sql statement with the proper type cast:

```sql
select * from tbl where id_as_uuid = $1::text
```

1. The reason the linter manually casts the type is to trigger an error if we're accidentally comparing different types. Leaving the parameter without any casting won't trigger an error.
2. While we can pass a `uuid` to a `text`, we can't do the opposite. It's like passing a `string` to a string literal (in some way).
3. During check time, the rule doesn't have context of where the expression is at. In other words, when the expression is being transpiled to `$1::text`, it doesn't know that it's in a comparison context of `tbl.id_as_uuid`.
