### ISSUE TITLE
Failing interpolation

### ISSUE THREAD

**Issue by Eprince-hub** [ts-safeql/safeql#56]
**Describe the bug**
When using `Postgres.js`, interpolation causes SafeQL error

**To Reproduce**
```ts
async function query(id: number) {
  type Animal = {
    id: number;
  };

// Works
  await sql<Animal[]>`SELECT * FROM animals WHERE id = 1`;

// Fail
  await sql<Animal[]>`SELECT * FROM animals WHERE id = ${id}`;
}
```

**Expected behavior**
Shouldn't fail with interpolation

**Screenshots**
![Screenshot 2022-09-26 at 16 37 10](https://user-images.githubusercontent.com/74430629/192304610-a46c0f3d-cc56-4761-b933-56f0260fd7c0.png)

![Screenshot 2022-09-26 at 16 24 08](https://user-images.githubusercontent.com/74430629/192304277-fadf5ee9-a23c-4a19-8f2f-aaf185d5fa1b.png)

**Desktop (please complete the following information):**
 - OS: Mac OS
 - PostgreSQL version 13

**Additional context**

**Comment by Newbie012** [comment]
Looks odd, since I have a test case and an actual demos as shown here https://github.com/ts-safeql/safeql/blob/main/demos/basic/src/index.ts

If you run eslint from the cli, do you still get that error message? Are you using the latest version?

**Comment by karlhorky** [comment]
I added an example of interpolation in Postgres.js in PR #59, maybe this will be a failing test for this issue

**Comment by Newbie012** [comment]
I think it's a problem with the vscode ESLint extension rather than ESLint itself.

How can it be reproduced?

**Comment by Eprince-hub** [comment]
I am getting the same error when i run eslint from the cli, I am using the latest version

The error is reproduced in this repo https://github.com/upleveled/next-js-example-spring-2022 in `add-safeql-plugin` branch

## Steps to reproduce

### Database Setup

You can install / setup PostgreSQL following the steps in [UpLeveled's System Setup Instructions](https://github.com/upleveled/system-setup/blob/master/readme.md).

If you have PostgreSQL already setup then connect to the built-in `postgres` database as administrator in order to create the database:

**Windows**
```bash
psql -U postgres
```

**macOS**
```bash
psql postgres
```

**Linux**
```bash
sudo -u postgres psql
```
If it asks for a password, use `postgres`.

Once you have connected, run the following to create the database:

```sql
CREATE DATABASE <database name>;
CREATE USER <user name> WITH ENCRYPTED PASSWORD '<user password>';
GRANT ALL PRIVILEGES ON DATABASE <database name> TO <user name>;
```

Quit `psql` using the following command:

```bash
\q
```

On Linux, you will also need to create a Linux system user with a name matching the user name you used in the database. It will prompt you to create a password for the user - choose the same password as for the database above.

```bash
sudo adduser <user name>
```
### Adding the environment variables

Copy the `.env.example` file to a new file called `.env` (ignored from Git) and fill in the necessary information.

### Running the migrations

This sets up the required table in the database

```bash
yarn migrate up
```

To reverse the last single migration, run:

```bash
yarn migrate down
```

**Comment by karlhorky** [comment]
@Newbie012 the whole PR is here: https://github.com/upleveled/next-js-example-spring-2022/pull/11

You can see the failing `eslint` command in this CI run: https://github.com/upleveled/next-js-example-spring-2022/actions/runs/3141711623/jobs/5104464969

<img width="1058" alt="Screen Shot 2022-09-28 at 10 19 50" src="https://user-images.githubusercontent.com/1935696/192727481-7d81caac-d16c-4db0-9401-6478afc41e6b.png">

**Comment by Newbie012** [comment]
I figured it out.

The error `there is no parameter ...` indicates that the query is actually being executed, which explains why when you ran `drop table` did actually drop the table.

This happens due to a bug that I reported [here](https://github.com/porsager/postgres/issues/424) in Postgres.js.

Luckily, a [fix](https://github.com/porsager/postgres/commit/3e47f0ace16875ef39b564d588dafe8e09d60bfd) was pushed, although there hasn't been a new release since May 26. [I opened an issue](https://github.com/porsager/postgres/issues/477) a few weeks ago that requests to publish a new release to npm.

The reason it didn't happen in my repository:

1. Currently, as a workaround for this issue, I'm installing the package directly from GitHub (which is not recommended)
2. I'm using PNPM instead of Yarn, which handles dependencies differently. I'm not an expert when it comes to package managers, but all I know is that when I installed from `github:porsager/postgres` and ran `yarn`, I still got an error. When I switched to PNPM, everything worked. I think it's since (I might be misleading tho) PNPM can download different versions of the same package.

My recommendations are -either install directly from GitHub and use PNPM instead. Or, wait until the maintainer of Postgres.js will create a new release and install it. Once he does, I should probably prevent users from using this plugin if they have a lower version for safety.

**Comment by Eprince-hub** [comment]
In Yarn you can specify a GitHub repo using the full url, this seems to work:
```bash
yarn add https://github.com/porsager/postgres
```

**Comment by porsager** [comment]
Sorry for the late release including the fix, but v3.3.0 is out now

**Comment by Newbie012** [comment]
Thanks @porsager !

**Comment by karlhorky** [comment]
Thanks @porsager ! Added a PR to update the versions to `^3.3.0` in all SafeQL packages: https://github.com/ts-safeql/safeql/issues/56#issuecomment-1263989878
